// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post_view.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPostView = `-- name: CreatePostView :one
INSERT INTO post_views(id, created_at, updated_at, user_id, post_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, post_id
`

type CreatePostViewParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

func (q *Queries) CreatePostView(ctx context.Context, arg CreatePostViewParams) (PostView, error) {
	row := q.db.QueryRowContext(ctx, createPostView,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
	)
	var i PostView
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}
